import setuptools

with open("README.md", "r") as fh:
    LONG_DESCRIPTION = fh.read()

setuptools.setup(
    name="django_editor_js",
    version="1.0.0",
    author="Nalin Dobhal",
    author_email="dobhalnalin@gmail.com",
    description="Renders json generated by editorjs.io as HTML content.",
    long_description=LONG_DESCRIPTION,
    long_description_content_type="text/markdown",
    url="https://github.com/nalindobhal/django_editor_js",
    packages=["django_editor_js"],
    include_package_data=True,
    install_requires=['django>=1.8'],
    classifiers=[
        "Development Status :: 2 - Pre-Alpha",
        "Programming Language :: Python :: 3",
        "Framework :: Django :: 3.0",
        "Environment :: Web Environment",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
    ],
)
